# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pokemon_3SC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pokemon_3SC
  use_frameworks!
  pod 'Alamofire'
  pod 'SDWebImageSwiftUI'

  target 'Pokemon_3SCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pokemon_3SCUITests' do
    # Pods for testing
  end

end
